(function(D){function w(e){return(e||getLocalDateString()).slice(0,8)+"01"}function $(e,n,o){return e?.length?e.filter(r=>{const t=(r.entry_date||r.transaction_date||r.date||"").toString();return!(!t||n&&t<n||o&&t>o)}):[]}function E(e){return(e||[]).reduce((n,o)=>n+Number(o.amount||0),0)}function p(e){return e?.length?[...e].sort((n,o)=>{const r=(n.entry_date||n.transaction_date||n.date||"").toString();return(o.entry_date||o.transaction_date||o.date||"").toString().localeCompare(r)}):[]}function A(e,n,o){if(!e?.id)return"";const r=e.amount!=null?String(e.amount):"",t=(e.transaction_date||e.entry_date||e.date||"").toString(),a=o?.idKey||"entryId";return AdminDelete.buttonHtml({selector:n||"credit-delete-btn",data:{[a]:e.id,amount:r,date:t},title:"Delete (admin)"})}function _(e,n,o){const r=!!o?.showAdminActions;return e?.length?n==="credit-rich"?e.map(t=>{const a=t.fuel_type?formatFuelBadge(t.fuel_type):"\u2014",d=t.quantity!=null?Number(t.quantity).toFixed(3):"\u2014",s=Number(t.amount_settled||0),c=Number(t.amount||0)-s,g=r&&t.id?`<td class="table-actions">${A(t,"credit-delete-entry")}</td>`:r?'<td class="table-actions muted">\u2014</td>':"";return`<tr>
            <td>${escapeHtml(formatDisplayDate(t.transaction_date||t.entry_date))}</td>
            <td>${a}</td>
            <td>${d}</td>
            <td>${formatCurrency(t.amount)}</td>
            <td>${formatCurrency(c)}</td>
            ${g}
          </tr>`}).join(""):n==="payment-rich"?e.map(t=>{const a=r?t.id?`<td class="table-actions">${A(t,"credit-delete-payment",{idKey:"paymentId"})}</td>`:'<td class="table-actions muted">\u2014</td>':"";return`<tr>
              <td>${escapeHtml(formatDisplayDate(t.date||t.entry_date))}</td>
              <td>${formatCurrency(t.amount)}</td>
              <td>${escapeHtml(t.payment_mode||"\u2014")}${t.same_day_settlement?' <span class="dc-same-day-tag">Same day settlement</span>':""}</td>
              <td>${escapeHtml(t.note||"\u2014")}</td>
              ${a}
            </tr>`}).join(""):e.map(t=>`<tr><td>${escapeHtml(formatDisplayDate(t.entry_date||t.date))}</td><td>${formatCurrency(t.amount)}</td></tr>`).join(""):""}function S(e,n,o,r,t,a,d){const s={entries:[],page:0,showAdminActions:!!d?.showAdminActions};function c(i){s.showAdminActions=!!i,l()}function l(){const i=s.entries.length,m=Math.max(1,Math.ceil(i/5)),f=Math.min(s.page,m-1);if(s.page=f,i===0){e&&(e.innerHTML=""),n&&n.classList.remove("hidden"),o&&o.classList.add("hidden");return}const h=f*5,y=Math.min(h+5,i),b=s.entries.slice(h,y),R=e?.dataset?.breakdownMode||"simple";e&&(e.innerHTML=_(b,R,{showAdminActions:s.showAdminActions})),n&&n.classList.add("hidden"),o&&r&&t&&a&&(o.classList.remove("hidden"),r.textContent=`Showing ${h+1}\u2013${y} of ${i}`,t.disabled=f<=0,t.classList.toggle("hidden",m<=1),a.disabled=f>=m-1,a.classList.toggle("hidden",m<=1))}function g(i){s.entries=p(i),s.page=0,l()}return t&&t.addEventListener("click",()=>{s.page>0&&(s.page--,l())}),a&&a.addEventListener("click",()=>{const i=Math.ceil(s.entries.length/5);s.page<i-1&&(s.page++,l())}),{setEntries:g,render:l,setAdminActions:c}}function u(e){return String(e?.entry_date||e?.transaction_date||e?.date||"")}function N(e){return u(e).slice(0,7)}function M(e,n,o){const r=new Map,t=(a,d)=>{const s=N(a);if(s.length!==7||s===o)return;const c=r.get(s)||{month:s,credit:0,settled:0};c[d]+=Number(a?.amount)||0,r.set(s,c)};for(const a of e||[])t(a,"credit");for(const a of n||[])t(a,"settled");return[...r.values()].sort((a,d)=>a.month.localeCompare(d.month))}function C(e,n,o){const r=new Map,t=(a,d)=>{const s=u(a);if(s.length<10||o&&s.slice(0,7)!==o)return;const c=r.get(s)||{date:s,credit:0,settled:0};c[d]+=Number(a?.amount)||0,r.set(s,c)};for(const a of e||[])t(a,"credit");for(const a of n||[])t(a,"settled");return[...r.values()].sort((a,d)=>a.date.localeCompare(d.date))}function L(e){return(e||[]).map(n=>{const o=Number(n?.amount)||0,r=Number(n?.amount_settled)||0;return{...n,amount:o,settled:r,open:o-r}}).filter(n=>n.open>.009).sort((n,o)=>u(n).localeCompare(u(o)))}D.CreditCustomerDetail={BREAKDOWN_PAGE_SIZE:5,getMonthStart:w,filterEntriesByRange:$,sumAmount:E,sortEntriesByDateDesc:p,renderBreakdownRows:_,createBreakdownPager:S,buildMonthActivityRows:M,buildDayActivityRows:C,openCreditLines:L}})(typeof window<"u"?window:globalThis);
