document.addEventListener("DOMContentLoaded",async()=>{const o=/^\d{4}-\d{2}-\d{2}$/,r=(()=>{try{const s=typeof sessionStorage<"u"?sessionStorage.getItem("petrolpump_sales_daily_from_dashboard"):null;if(s&&o.test(s))return sessionStorage.removeItem("petrolpump_sales_daily_from_dashboard"),s}catch{}return null})(),e=(()=>{const s=new URLSearchParams(window.location.search).get("date");return s&&o.test(s)?s:null})(),t=await requireAuth({allowedRoles:["admin","supervisor"],onDenied:"dashboard.html",pageName:"sales-daily"});if(!t)return;applyRoleVisibility(t.role),typeof initPageSections=="function"&&initPageSections({defaultSection:"filters",validSections:["filters","petrol","diesel"]});const a=document.getElementById("sales-start-date"),n=document.getElementById("sales-end-date"),g=new Date,u=getLocalDateString(),p=g.getFullYear(),i=g.getMonth(),c=s=>String(s).padStart(2,"0"),d={start:`${p}-${c(i+1)}-01`,end:`${p}-${c(i+1)}-${c(new Date(p,i+1,0).getDate())}`};if(a&&n){const s=new Set(["custom"]),l=typeof window.getValidFilterState=="function"?window.getValidFilterState("sales_daily",s):null,m=r||e;m?(a.value=m,n.value=m,window.setFilterState&&window.setFilterState("sales_daily",{range:"custom",start:m,end:m})):l&&l.start&&l.end?(a.value=l.start,n.value=l.end):(a.value=d.start,n.value=d.end);const y=()=>{window.setFilterState&&window.setFilterState("sales_daily",{range:"custom",start:a.value||void 0,end:n.value||void 0})},f=()=>{const _=a.value||u,$=n.value||u;loadDailySummary(_,$),y()};a.addEventListener("change",f),n.addEventListener("change",f),loadDailySummary(a.value,n.value)}});const TABLE_COLS=11;function setProductTableLoading(o){o.innerHTML=`<tr><td colspan="${TABLE_COLS}" class="muted">Loading\u2026</td></tr>`}function renderProductRows(o,r){if(!r.length){o.innerHTML=`<tr><td colspan="${TABLE_COLS}" class="muted">No entries found.</td></tr>`;return}o.innerHTML=r.map(e=>{const t=getDsrNetSaleLitres(e);return`<tr>
        <td>${escapeHtml(e.date)}</td>
        <td>${formatQuantity(e.sales_pump1)}</td>
        <td>${formatQuantity(e.sales_pump2)}</td>
        <td>${formatQuantity(e.total_sales)}</td>
        <td>${formatQuantity(e.testing)}</td>
        <td>${formatQuantity(t)}</td>
        <td>${formatQuantity(e.stock)}</td>
        <td>${formatQuantity(e.opening_stock)}</td>
        <td>${formatQuantity(e.receipts)}</td>
        <td>${formatQuantity(e.closing_stock)}</td>
        <td>${formatQuantity(e.variation)}</td>
      </tr>`}).join("")}async function loadDailySummary(o,r){const e=document.getElementById("sales-daily-petrol-body"),t=document.getElementById("sales-daily-diesel-body");if(!e||!t)return;setProductTableLoading(e),setProductTableLoading(t);const[{data:a,error:n},{data:g,error:u}]=await Promise.all([supabaseClient.from("dsr").select("date, product, sales_pump1, sales_pump2, total_sales, testing, stock").gte("date",o).lte("date",r).order("date",{ascending:!1}),supabaseClient.rpc("get_dsr_stock_range",{p_start:o,p_end:r})]);if(n||u){const d=n||u;AppError.report(d,{context:"salesDailyLoad"});const s=escapeHtml(AppError.getUserMessage(d)),l=`<tr><td colspan="${TABLE_COLS}" class="error">${s}</td></tr>`;e.innerHTML=l,t.innerHTML=l;return}const p=mergeDailyData(a??[],g??[]),i=[],c=[];for(const d of p){const s=(d.product||"").toLowerCase();s==="petrol"?i.push(d):s==="diesel"&&c.push(d)}renderProductRows(e,i),renderProductRows(t,c)}function mergeDailyData(o,r){const e=new Map;return o.forEach(t=>{const a=`${t.date}-${t.product}`;e.set(a,{date:t.date,product:t.product,sales_pump1:t.sales_pump1,sales_pump2:t.sales_pump2,total_sales:t.total_sales,testing:t.testing,stock:t.stock})}),r.forEach(t=>{const a=`${t.date}-${t.product}`,n=e.get(a)||{date:t.date,product:t.product};e.set(a,{...n,opening_stock:t.opening_stock,receipts:t.receipts,closing_stock:t.closing_stock,variation:t.variation})}),Array.from(e.values()).sort((t,a)=>t.date===a.date?t.product.localeCompare(a.product):a.date.localeCompare(t.date))}
