(function(C){async function v(t,n){const i=String(t||"").trim();if(!i)return null;const a=d=>{let p=supabaseClient.from("invoice_documents").select("id").eq("category","purchase").eq("title",i).order("invoice_date",{ascending:!1}).limit(1);return d&&n&&(p=p.eq("invoice_date",n)),p};let{data:s,error:r}=await a(!0);if(!r&&s?.[0]?.id||n&&({data:s,error:r}=await a(!1),!r&&s?.[0]?.id))return s[0].id;const f=`%${i.replace(/[%_\\]/g,"\\$&")}%`;let u=supabaseClient.from("invoice_documents").select("id, title").eq("category","purchase").ilike("title",f).order("invoice_date",{ascending:!1}).limit(10);n&&(u=u.eq("invoice_date",n));const e=await u;if(e.error||!e.data?.length)return n?v(i,null):null;const o=i.toLowerCase(),l=e.data.find(d=>String(d.title||"").trim().toLowerCase()===o);return l?l.id:e.data.find(d=>String(d.title||"").toLowerCase().includes(o))?.id??null}function g(t,n){t&&(t.textContent=n,t.classList.remove("hidden"))}function $(t){t?.classList.add("hidden")}function L(t,n){const{listEl:i,alertEl:a,emptyEl:s,errorEl:r,onSaved:f}=n;if(!i)return;if($(r),!t?.length){a?.classList.add("hidden"),i.innerHTML="",s?.classList.remove("hidden");return}s?.classList.add("hidden"),a?.classList.remove("hidden");const u=PumpSettings.getCachedSync().reports?.fuelSupplierGstin||AppConfig.DEFAULT_REPORTS.fuelSupplierGstin||"";i.innerHTML=t.map(e=>{const o=normalizeProduct(e.product)==="petrol"?"Petrol":"Diesel",l=e.id,y=escapeHtml(e.supplier_invoice_no||""),d=escapeHtml(e.supplier_gstin||u||"");return`
        <li class="pl-missing-item" data-dsr-id="${escapeHtml(l)}" data-product="${escapeHtml(normalizeProduct(e.product))}" data-date="${escapeHtml(e.date)}">
          <span class="pl-missing-label">${escapeHtml(e.date)} \xB7 ${o}</span>
          <label for="pl-buying-${l}" class="sr-only">${escapeHtml(getPlBuyingPriceFieldLabel())}</label>
          <input id="pl-buying-${l}" type="number" inputmode="decimal" step="0.01" min="0" placeholder="${escapeHtml(getPlBuyingPricePlaceholder())}" class="pl-buying-input" data-dsr-id="${escapeHtml(l)}" />
          <label for="pl-inv-${l}" class="sr-only">Supplier invoice no</label>
          <input id="pl-inv-${l}" type="text" maxlength="40" placeholder="BPCL invoice no" class="pl-inv-input" value="${y}" data-dsr-id="${escapeHtml(l)}" />
          <label for="pl-gstin-${l}" class="sr-only">Supplier GSTIN</label>
          <input id="pl-gstin-${l}" type="text" maxlength="15" placeholder="Supplier GSTIN" class="pl-gstin-input" value="${d}" data-dsr-id="${escapeHtml(l)}" />
          <button type="button" class="button-secondary pl-buying-save" data-dsr-id="${escapeHtml(l)}" data-product="${escapeHtml(normalizeProduct(e.product))}">Save</button>
        </li>`}).join(""),i.querySelectorAll(".pl-buying-save").forEach(e=>{e.addEventListener("click",()=>B(e.dataset.dsrId,n))})}async function B(t,n){const{listEl:i,errorEl:a,onSaved:s}=n,r=document.getElementById(`pl-buying-${t}`),f=document.getElementById(`pl-inv-${t}`),u=document.getElementById(`pl-gstin-${t}`),e=i?.querySelector(`.pl-buying-save[data-dsr-id="${t}"]`),o=i?.querySelector(`.pl-missing-item[data-dsr-id="${t}"]`),l=e?.dataset?.product||o?.dataset?.product,y=o?.dataset?.date||null,d=Number.parseFloat((r?.value??"").trim()),p=validateBuyingRateKlInput(d);if(!p.ok){g(a,p.message||`Enter a valid ${getPlBuyingPriceFieldLabel().toLowerCase()}.`);return}const _=buyingRatePerLitreForDb(p.valuePerLitre,l);if(_==null){g(a,`Enter a valid ${getPlBuyingPriceFieldLabel().toLowerCase()}.`);return}const b=(f?.value??"").trim();let m=(u?.value??"").trim().toUpperCase();if(m||(m=(PumpSettings.getCachedSync().reports?.fuelSupplierGstin||AppConfig.DEFAULT_REPORTS.fuelSupplierGstin||"").toString().trim().toUpperCase()),m&&!/^[0-9A-Z]{15}$/.test(m)){g(a,"Supplier GSTIN must be 15 characters (or leave blank).");return}$(a);const c=e,P=()=>{c&&(c.disabled=!1,c.textContent="Save",c.classList.remove("pl-save-success"))};c&&(c.disabled=!0,c.textContent="Saving\u2026");let S=null;try{b&&(S=await v(b,y||null))}catch{S=null}const h=await supabaseClient.rpc("update_dsr_buying_price",{p_dsr_id:t,p_value:_,p_supplier_invoice_no:b||null,p_supplier_gstin:m||null,p_invoice_document_id:S});if(h.error){AppError.report(h.error,{context:"handleSaveBuyingPrice",type:"dsr"}),g(a,h.error.message||"Could not save. Ensure you are logged in as admin."),P();return}c&&(c.textContent="Saved",c.classList.add("pl-save-success")),typeof AppCache<"u"&&AppCache&&CacheInvalidation.invalidate("dsr"),typeof s=="function"?await s():await E({...n,force:!0}),P()}async function E(t={}){const{force:n=!1,listEl:i,alertEl:a,emptyEl:s,errorEl:r,onSaved:f}=t,{data:u,error:e}=await DsrQueries.fetchMissingBuyingPriceRows({force:n});if(e)return AppError.report(e,{context:"BuyingPriceEntry.refresh"}),i&&(i.innerHTML=""),a?.classList.add("hidden"),s?.classList.add("hidden"),g(r,e.message||"Could not load receipt days needing a buying price."),[];const o=u??[];return L(o,{listEl:i,alertEl:a,emptyEl:s,errorEl:r,onSaved:f}),o}function H(){document.querySelector(".pl-buying-input")?.focus({preventScroll:!0})}C.BuyingPriceEntry={findVaultDocumentIdForInvoice:v,renderMissingBuyingList:L,refresh:E,focusFirstInput:H}})(typeof window<"u"?window:globalThis);
