(function(D){function y(e){return(e||getLocalDateString()).slice(0,8)+"01"}function $(e,n,a){return e?.length?e.filter(i=>{const t=(i.entry_date||i.transaction_date||i.date||"").toString();return!(!t||n&&t<n||a&&t>a)}):[]}function w(e){return(e||[]).reduce((n,a)=>n+Number(a.amount||0),0)}function g(e){return e?.length?[...e].sort((n,a)=>{const i=(n.entry_date||n.transaction_date||n.date||"").toString();return(a.entry_date||a.transaction_date||a.date||"").toString().localeCompare(i)}):[]}function h(e,n,a){if(!e?.id)return"";const i=e.amount!=null?String(e.amount):"",t=(e.transaction_date||e.entry_date||e.date||"").toString(),s=a?.idKey||"entryId";return AdminDelete.buttonHtml({selector:n||"credit-delete-btn",data:{[s]:e.id,amount:i,date:t},title:"Delete (admin)"})}function _(e,n,a){const i=!!a?.showAdminActions;return e?.length?n==="credit-rich"?e.map(t=>{const s=t.fuel_type?formatFuelBadge(t.fuel_type):"\u2014",u=t.quantity!=null?Number(t.quantity).toFixed(3):"\u2014",d=Number(t.amount_settled||0),m=Number(t.amount||0)-d,f=i&&t.id?`<td class="table-actions">${h(t,"credit-delete-entry")}</td>`:i?'<td class="table-actions muted">\u2014</td>':"";return`<tr>
            <td>${escapeHtml(formatDisplayDate(t.transaction_date||t.entry_date))}</td>
            <td>${s}</td>
            <td>${u}</td>
            <td>${formatCurrency(t.amount)}</td>
            <td>${formatCurrency(m)}</td>
            ${f}
          </tr>`}).join(""):n==="payment-rich"?e.map(t=>{const s=i?t.id?`<td class="table-actions">${h(t,"credit-delete-payment",{idKey:"paymentId"})}</td>`:'<td class="table-actions muted">\u2014</td>':"";return`<tr>
              <td>${escapeHtml(formatDisplayDate(t.date||t.entry_date))}</td>
              <td>${formatCurrency(t.amount)}</td>
              <td>${escapeHtml(t.payment_mode||"\u2014")}</td>
              <td>${escapeHtml(t.note||"\u2014")}</td>
              ${s}
            </tr>`}).join(""):e.map(t=>`<tr><td>${escapeHtml(formatDisplayDate(t.entry_date||t.date))}</td><td>${formatCurrency(t.amount)}</td></tr>`).join(""):""}function E(e,n,a,i,t,s,u){const d={entries:[],page:0,showAdminActions:!!u?.showAdminActions};function m(r){d.showAdminActions=!!r,o()}function o(){const r=d.entries.length,c=Math.max(1,Math.ceil(r/5)),l=Math.min(d.page,c-1);if(d.page=l,r===0){e&&(e.innerHTML=""),n&&n.classList.remove("hidden"),a&&a.classList.add("hidden");return}const A=l*5,p=Math.min(A+5,r),S=d.entries.slice(A,p),L=e?.dataset?.breakdownMode||"simple";e&&(e.innerHTML=_(S,L,{showAdminActions:d.showAdminActions})),n&&n.classList.add("hidden"),a&&i&&t&&s&&(a.classList.remove("hidden"),i.textContent=`Showing ${A+1}\u2013${p} of ${r}`,t.disabled=l<=0,t.classList.toggle("hidden",c<=1),s.disabled=l>=c-1,s.classList.toggle("hidden",c<=1))}function f(r){d.entries=g(r),d.page=0,o()}return t&&t.addEventListener("click",()=>{d.page>0&&(d.page--,o())}),s&&s.addEventListener("click",()=>{const r=Math.ceil(d.entries.length/5);d.page<r-1&&(d.page++,o())}),{setEntries:f,render:o,setAdminActions:m}}D.CreditCustomerDetail={BREAKDOWN_PAGE_SIZE:5,getMonthStart:y,filterEntriesByRange:$,sumAmount:w,sortEntriesByDateDesc:g,renderBreakdownRows:_,createBreakdownPager:E}})(typeof window<"u"?window:globalThis);
